### ISSUE TITLE
Ingress Support

### ISSUE THREAD

**Issue by mdrews93** [sztupy/hassio-actualbudget#3] opened 2024-02-13 19:38 UTC
Ingress support would be nice for this add-on. I'm currently running into an issue accessing the web UI and I suspect I would be able to with ingress as I'm able to access other ingress add-ons. I'm not too familiar with ingress or addon development, this looks like a good start:

https://developers.home-assistant.io/docs/add-ons/presentation/#ingress

It might not be much more than adding `ingress: true` to _config.yaml_. Still need to look into it some more.

**Comment by sztupy** [comment] 2024-02-15 10:30
`ingress: true` doesn't set up HTTPS with a proper certificate that Actual requires. I can play around to see if I can make it work though

**Comment by sztupy** [comment] 2024-05-03 20:34
Closing as a duplicate of https://github.com/sztupy/hassio-actualbudget/issues/5

**Closed as not planned by sztupy** 2024-05-03 20:34 UTC
